export type EventType = {
  id: number;
  title: string;
  music_style: string;
  bar_name: string;
  image: string;
  hour_only: number;
  latitude: number;
  longitude: number;
  description: string;
  date: number;
  address: string;
  postcode: string;
  city: string;
  group_id: number;
  music_group_name: string;
  music_group_id: number;
  start_at: string;
  end_at: string;
};
