version: "3.4"

services:
  web:
    #build: .
    image: ghcr.io/tcrusel/song_2_bar:latest
    ports:
      - "3310:3310"
      - "3000:3000"
    environment:
      APP_PORT: 3310
      APP_SECRET: 123456789
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: song2bar
      VITE_API_URL: "http://localhost:3310"
      SEED_DB: "true"
    command: >
      sh -c '
        npm run db:migrate || echo "pas de script migrate (ok)";
        npm run db:seed;
        npm run dev
      '
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql/mysql-server:8.0
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uuser", "-ppassword" ] # Command to check health.
      interval: 5s # Interval between health checks.
      timeout: 5s # Timeout for each health checking.
      retries: 20 # Hou many times retries.
      start_period: 10s
    volumes:
      - ./database-setup.sh:/docker-entrypoint-initdb.d/setup.sh
      #- /tmp/db-data:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3306
      # Password for root access
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "127.0.0.1:3308:3306/tcp"

