name: deploy-main

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest
      - name: Docker build
        run: | 
          echo "lancement du docker build"
          docker compose build

  # deploy:
  #   name: Deploiment prod
  #   needs: [check]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Install Docker Compose
  #       uses: docker/setup-compose-action@v1
  #       with:
  #         version: latest
