name: deploy-main

on:
  push:
    branches:
      - main
jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
